version: '3.4'

services:

  db:
    image: postgres:14.1-alpine
    container_name: dbaas
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'